# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'viewer.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QLCDNumber,
    QLabel, QMainWindow, QMenuBar, QPushButton,
    QRadioButton, QScrollArea, QSizePolicy, QSlider,
    QStatusBar, QTabWidget, QVBoxLayout, QWidget)

from MPLWidget import MPLWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(0, 144, 255, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush)
        brush1 = QBrush(QColor(145, 145, 145, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Highlight, brush1)
        self.centralwidget.setPalette(palette)
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.VisualizerBox = QGroupBox(self.centralwidget)
        self.VisualizerBox.setObjectName(u"VisualizerBox")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(5)
        sizePolicy1.setVerticalStretch(1)
        sizePolicy1.setHeightForWidth(self.VisualizerBox.sizePolicy().hasHeightForWidth())
        self.VisualizerBox.setSizePolicy(sizePolicy1)
        self.verticalLayout = QVBoxLayout(self.VisualizerBox)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.mpl_widget = MPLWidget(self.VisualizerBox)
        self.mpl_widget.setObjectName(u"mpl_widget")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(15)
        sizePolicy2.setHeightForWidth(self.mpl_widget.sizePolicy().hasHeightForWidth())
        self.mpl_widget.setSizePolicy(sizePolicy2)
        self.mpl_widget.setMinimumSize(QSize(400, 400))

        self.verticalLayout.addWidget(self.mpl_widget)

        self.gb_visualizer = QGroupBox(self.VisualizerBox)
        self.gb_visualizer.setObjectName(u"gb_visualizer")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(1)
        sizePolicy3.setHeightForWidth(self.gb_visualizer.sizePolicy().hasHeightForWidth())
        self.gb_visualizer.setSizePolicy(sizePolicy3)
        self.gb_visualizer.setToolTipDuration(0)
        self.gb_visualizer.setAutoFillBackground(False)
        self.gb_visualizer.setFlat(False)
        self.gb_visualizer.setCheckable(False)
        self.gb_visualizer.setChecked(False)
        self.horizontalLayout = QHBoxLayout(self.gb_visualizer)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.load_image_pushbutton = QPushButton(self.gb_visualizer)
        self.load_image_pushbutton.setObjectName(u"load_image_pushbutton")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(3)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.load_image_pushbutton.sizePolicy().hasHeightForWidth())
        self.load_image_pushbutton.setSizePolicy(sizePolicy4)
        self.load_image_pushbutton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.load_image_pushbutton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.load_image_pushbutton.setIcon(icon)
        self.load_image_pushbutton.setFlat(False)

        self.horizontalLayout.addWidget(self.load_image_pushbutton)

        self.clear_image_pushbutton = QPushButton(self.gb_visualizer)
        self.clear_image_pushbutton.setObjectName(u"clear_image_pushbutton")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy5.setHorizontalStretch(1)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.clear_image_pushbutton.sizePolicy().hasHeightForWidth())
        self.clear_image_pushbutton.setSizePolicy(sizePolicy5)
        self.clear_image_pushbutton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ApplicationExit))
        self.clear_image_pushbutton.setIcon(icon1)

        self.horizontalLayout.addWidget(self.clear_image_pushbutton)


        self.verticalLayout.addWidget(self.gb_visualizer)


        self.gridLayout.addWidget(self.VisualizerBox, 0, 0, 1, 1)

        self.ControlsBox = QGroupBox(self.centralwidget)
        self.ControlsBox.setObjectName(u"ControlsBox")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy6.setHorizontalStretch(2)
        sizePolicy6.setVerticalStretch(3)
        sizePolicy6.setHeightForWidth(self.ControlsBox.sizePolicy().hasHeightForWidth())
        self.ControlsBox.setSizePolicy(sizePolicy6)
        self.verticalLayout_2 = QVBoxLayout(self.ControlsBox)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.sliders_groupbox = QGroupBox(self.ControlsBox)
        self.sliders_groupbox.setObjectName(u"sliders_groupbox")
        sizePolicy3.setHeightForWidth(self.sliders_groupbox.sizePolicy().hasHeightForWidth())
        self.sliders_groupbox.setSizePolicy(sizePolicy3)
        self.gridLayout_2 = QGridLayout(self.sliders_groupbox)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setVerticalSpacing(8)
        self.gridLayout_2.setContentsMargins(12, 12, 12, 12)
        self.stroke_width_slider = QSlider(self.sliders_groupbox)
        self.stroke_width_slider.setObjectName(u"stroke_width_slider")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy7.setHorizontalStretch(4)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.stroke_width_slider.sizePolicy().hasHeightForWidth())
        self.stroke_width_slider.setSizePolicy(sizePolicy7)
        self.stroke_width_slider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.stroke_width_slider.setMinimum(1)
        self.stroke_width_slider.setMaximum(1000)
        self.stroke_width_slider.setSingleStep(1)
        self.stroke_width_slider.setPageStep(1)
        self.stroke_width_slider.setValue(100)
        self.stroke_width_slider.setSliderPosition(100)
        self.stroke_width_slider.setOrientation(Qt.Orientation.Horizontal)
        self.stroke_width_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.stroke_width_slider.setTickInterval(1)

        self.gridLayout_2.addWidget(self.stroke_width_slider, 1, 0, 1, 1)

        self.isovalue_label = QLabel(self.sliders_groupbox)
        self.isovalue_label.setObjectName(u"isovalue_label")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy8.setHorizontalStretch(4)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.isovalue_label.sizePolicy().hasHeightForWidth())
        self.isovalue_label.setSizePolicy(sizePolicy8)
        self.isovalue_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.isovalue_label, 2, 0, 1, 1)

        self.isovalue_display = QLCDNumber(self.sliders_groupbox)
        self.isovalue_display.setObjectName(u"isovalue_display")
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy9.setHorizontalStretch(1)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.isovalue_display.sizePolicy().hasHeightForWidth())
        self.isovalue_display.setSizePolicy(sizePolicy9)
        self.isovalue_display.setFrameShape(QFrame.Shape.StyledPanel)
        self.isovalue_display.setFrameShadow(QFrame.Shadow.Plain)
        self.isovalue_display.setSmallDecimalPoint(True)
        self.isovalue_display.setDigitCount(5)
        self.isovalue_display.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.isovalue_display.setProperty(u"value", 2.000000000000000)
        self.isovalue_display.setProperty(u"intValue", 2)

        self.gridLayout_2.addWidget(self.isovalue_display, 3, 1, 1, 1)

        self.isovalue_slider = QSlider(self.sliders_groupbox)
        self.isovalue_slider.setObjectName(u"isovalue_slider")
        sizePolicy7.setHeightForWidth(self.isovalue_slider.sizePolicy().hasHeightForWidth())
        self.isovalue_slider.setSizePolicy(sizePolicy7)
        self.isovalue_slider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.isovalue_slider.setMaximum(1000)
        self.isovalue_slider.setValue(100)
        self.isovalue_slider.setSliderPosition(100)
        self.isovalue_slider.setOrientation(Qt.Orientation.Horizontal)
        self.isovalue_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.isovalue_slider.setTickInterval(50)

        self.gridLayout_2.addWidget(self.isovalue_slider, 3, 0, 1, 1)

        self.stroke_width_label = QLabel(self.sliders_groupbox)
        self.stroke_width_label.setObjectName(u"stroke_width_label")
        sizePolicy10 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy10.setHorizontalStretch(4)
        sizePolicy10.setVerticalStretch(0)
        sizePolicy10.setHeightForWidth(self.stroke_width_label.sizePolicy().hasHeightForWidth())
        self.stroke_width_label.setSizePolicy(sizePolicy10)
        self.stroke_width_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.stroke_width_label, 0, 0, 1, 1)

        self.object_angle_slider = QSlider(self.sliders_groupbox)
        self.object_angle_slider.setObjectName(u"object_angle_slider")
        sizePolicy11 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy11.setHorizontalStretch(0)
        sizePolicy11.setVerticalStretch(0)
        sizePolicy11.setHeightForWidth(self.object_angle_slider.sizePolicy().hasHeightForWidth())
        self.object_angle_slider.setSizePolicy(sizePolicy11)
        self.object_angle_slider.setMaximum(1000)
        self.object_angle_slider.setValue(0)
        self.object_angle_slider.setSliderPosition(0)
        self.object_angle_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_2.addWidget(self.object_angle_slider, 5, 0, 1, 1)

        self.stroke_width_display = QLCDNumber(self.sliders_groupbox)
        self.stroke_width_display.setObjectName(u"stroke_width_display")
        sizePolicy9.setHeightForWidth(self.stroke_width_display.sizePolicy().hasHeightForWidth())
        self.stroke_width_display.setSizePolicy(sizePolicy9)
        self.stroke_width_display.setFrameShape(QFrame.Shape.StyledPanel)
        self.stroke_width_display.setFrameShadow(QFrame.Shadow.Plain)
        self.stroke_width_display.setSmallDecimalPoint(True)
        self.stroke_width_display.setDigitCount(6)
        self.stroke_width_display.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.stroke_width_display.setProperty(u"value", 1.000000000000000)
        self.stroke_width_display.setProperty(u"intValue", 1)

        self.gridLayout_2.addWidget(self.stroke_width_display, 1, 1, 1, 1)

        self.label = QLabel(self.sliders_groupbox)
        self.label.setObjectName(u"label")
        sizePolicy10.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy10)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)

        self.object_angle_display = QLCDNumber(self.sliders_groupbox)
        self.object_angle_display.setObjectName(u"object_angle_display")
        sizePolicy12 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy12.setHorizontalStretch(0)
        sizePolicy12.setVerticalStretch(0)
        sizePolicy12.setHeightForWidth(self.object_angle_display.sizePolicy().hasHeightForWidth())
        self.object_angle_display.setSizePolicy(sizePolicy12)
        self.object_angle_display.setFrameShape(QFrame.Shape.StyledPanel)
        self.object_angle_display.setFrameShadow(QFrame.Shadow.Plain)
        self.object_angle_display.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.object_angle_display.setProperty(u"value", 1.000000000000000)

        self.gridLayout_2.addWidget(self.object_angle_display, 5, 1, 1, 1)

        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 2)
        self.gridLayout_2.setRowStretch(2, 1)
        self.gridLayout_2.setRowStretch(3, 2)
        self.gridLayout_2.setRowStretch(4, 1)
        self.gridLayout_2.setRowStretch(5, 2)
        self.gridLayout_2.setRowMinimumHeight(0, 1)
        self.gridLayout_2.setRowMinimumHeight(1, 2)
        self.gridLayout_2.setRowMinimumHeight(2, 1)
        self.gridLayout_2.setRowMinimumHeight(3, 2)
        self.gridLayout_2.setRowMinimumHeight(4, 1)
        self.gridLayout_2.setRowMinimumHeight(5, 2)

        self.verticalLayout_2.addWidget(self.sliders_groupbox)

        self.ImageOptionsBox = QGroupBox(self.ControlsBox)
        self.ImageOptionsBox.setObjectName(u"ImageOptionsBox")
        sizePolicy13 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy13.setHorizontalStretch(0)
        sizePolicy13.setVerticalStretch(8)
        sizePolicy13.setHeightForWidth(self.ImageOptionsBox.sizePolicy().hasHeightForWidth())
        self.ImageOptionsBox.setSizePolicy(sizePolicy13)
        self.verticalLayout_4 = QVBoxLayout(self.ImageOptionsBox)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.ImageTabWidget = QTabWidget(self.ImageOptionsBox)
        self.ImageTabWidget.setObjectName(u"ImageTabWidget")
        sizePolicy14 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy14.setHorizontalStretch(0)
        sizePolicy14.setVerticalStretch(1)
        sizePolicy14.setHeightForWidth(self.ImageTabWidget.sizePolicy().hasHeightForWidth())
        self.ImageTabWidget.setSizePolicy(sizePolicy14)
        self.ImageTabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.ImageTabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.ImageTabWidget.setElideMode(Qt.TextElideMode.ElideNone)
        self.ImageTabWidget.setUsesScrollButtons(False)
        self.ImageTabWidget.setDocumentMode(False)
        self.ImageTabWidget.setTabsClosable(False)
        self.ImageTabWidget.setMovable(False)
        self.ImageTabWidget.setTabBarAutoHide(False)
        self.ImageVisualizationTab = QWidget()
        self.ImageVisualizationTab.setObjectName(u"ImageVisualizationTab")
        self.ImageVisualizationTab.setMouseTracking(False)
        self.gridLayout_3 = QGridLayout(self.ImageVisualizationTab)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.scrollArea_2 = QScrollArea(self.ImageVisualizationTab)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        sizePolicy15 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Expanding)
        sizePolicy15.setHorizontalStretch(0)
        sizePolicy15.setVerticalStretch(0)
        sizePolicy15.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy15)
        self.scrollArea_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.scrollArea_2.setFrameShadow(QFrame.Shadow.Plain)
        self.scrollArea_2.setLineWidth(0)
        self.scrollArea_2.setMidLineWidth(0)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 188, 120))
        self.verticalLayout_7 = QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.original_image_radiobutton = QRadioButton(self.scrollAreaWidgetContents_2)
        self.original_image_radiobutton.setObjectName(u"original_image_radiobutton")
        sizePolicy12.setHeightForWidth(self.original_image_radiobutton.sizePolicy().hasHeightForWidth())
        self.original_image_radiobutton.setSizePolicy(sizePolicy12)
        self.original_image_radiobutton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout_7.addWidget(self.original_image_radiobutton)

        self.distance_radiobutton = QRadioButton(self.scrollAreaWidgetContents_2)
        self.distance_radiobutton.setObjectName(u"distance_radiobutton")
        sizePolicy12.setHeightForWidth(self.distance_radiobutton.sizePolicy().hasHeightForWidth())
        self.distance_radiobutton.setSizePolicy(sizePolicy12)
        self.distance_radiobutton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout_7.addWidget(self.distance_radiobutton)

        self.clean_canvas_radiobutton = QRadioButton(self.scrollAreaWidgetContents_2)
        self.clean_canvas_radiobutton.setObjectName(u"clean_canvas_radiobutton")
        sizePolicy12.setHeightForWidth(self.clean_canvas_radiobutton.sizePolicy().hasHeightForWidth())
        self.clean_canvas_radiobutton.setSizePolicy(sizePolicy12)

        self.verticalLayout_7.addWidget(self.clean_canvas_radiobutton)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.gridLayout_3.addWidget(self.scrollArea_2, 0, 0, 1, 1)

        self.ImageTabWidget.addTab(self.ImageVisualizationTab, "")
        self.upsampling_tab = QWidget()
        self.upsampling_tab.setObjectName(u"upsampling_tab")
        self.verticalLayout_8 = QVBoxLayout(self.upsampling_tab)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.upsampling_combobox = QComboBox(self.upsampling_tab)
        self.upsampling_combobox.addItem("")
        self.upsampling_combobox.addItem("")
        self.upsampling_combobox.addItem("")
        self.upsampling_combobox.setObjectName(u"upsampling_combobox")
        self.upsampling_combobox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout_8.addWidget(self.upsampling_combobox)

        self.ImageTabWidget.addTab(self.upsampling_tab, "")

        self.verticalLayout_4.addWidget(self.ImageTabWidget)

        self.OverlaysTabWidget = QTabWidget(self.ImageOptionsBox)
        self.OverlaysTabWidget.setObjectName(u"OverlaysTabWidget")
        sizePolicy14.setHeightForWidth(self.OverlaysTabWidget.sizePolicy().hasHeightForWidth())
        self.OverlaysTabWidget.setSizePolicy(sizePolicy14)
        self.OverlaysTabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.OverlaysTabWidget.setElideMode(Qt.TextElideMode.ElideNone)
        self.OverlaysTab = QWidget()
        self.OverlaysTab.setObjectName(u"OverlaysTab")
        self.verticalLayout_3 = QVBoxLayout(self.OverlaysTab)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.scrollArea = QScrollArea(self.OverlaysTab)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy16 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Preferred)
        sizePolicy16.setHorizontalStretch(0)
        sizePolicy16.setVerticalStretch(0)
        sizePolicy16.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy16)
        self.scrollArea.setFrameShape(QFrame.Shape.StyledPanel)
        self.scrollArea.setFrameShadow(QFrame.Shadow.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 172, 129))
        self.verticalLayout_5 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.voronoi_diagram_checkbox = QCheckBox(self.scrollAreaWidgetContents)
        self.voronoi_diagram_checkbox.setObjectName(u"voronoi_diagram_checkbox")
        sizePolicy17 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy17.setHorizontalStretch(0)
        sizePolicy17.setVerticalStretch(0)
        sizePolicy17.setHeightForWidth(self.voronoi_diagram_checkbox.sizePolicy().hasHeightForWidth())
        self.voronoi_diagram_checkbox.setSizePolicy(sizePolicy17)
        self.voronoi_diagram_checkbox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout_5.addWidget(self.voronoi_diagram_checkbox)

        self.level_set_contour_checkbox = QCheckBox(self.scrollAreaWidgetContents)
        self.level_set_contour_checkbox.setObjectName(u"level_set_contour_checkbox")
        sizePolicy12.setHeightForWidth(self.level_set_contour_checkbox.sizePolicy().hasHeightForWidth())
        self.level_set_contour_checkbox.setSizePolicy(sizePolicy12)
        self.level_set_contour_checkbox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout_5.addWidget(self.level_set_contour_checkbox)

        self.object_angle_checkbox = QCheckBox(self.scrollAreaWidgetContents)
        self.object_angle_checkbox.setObjectName(u"object_angle_checkbox")
        sizePolicy18 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy18.setHorizontalStretch(0)
        sizePolicy18.setVerticalStretch(0)
        sizePolicy18.setHeightForWidth(self.object_angle_checkbox.sizePolicy().hasHeightForWidth())
        self.object_angle_checkbox.setSizePolicy(sizePolicy18)

        self.verticalLayout_5.addWidget(self.object_angle_checkbox)

        self.circumradius_checkbox = QCheckBox(self.scrollAreaWidgetContents)
        self.circumradius_checkbox.setObjectName(u"circumradius_checkbox")
        sizePolicy12.setHeightForWidth(self.circumradius_checkbox.sizePolicy().hasHeightForWidth())
        self.circumradius_checkbox.setSizePolicy(sizePolicy12)

        self.verticalLayout_5.addWidget(self.circumradius_checkbox)

        self.stroke_graph_checkbox = QCheckBox(self.scrollAreaWidgetContents)
        self.stroke_graph_checkbox.setObjectName(u"stroke_graph_checkbox")
        sizePolicy12.setHeightForWidth(self.stroke_graph_checkbox.sizePolicy().hasHeightForWidth())
        self.stroke_graph_checkbox.setSizePolicy(sizePolicy12)
        self.stroke_graph_checkbox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout_5.addWidget(self.stroke_graph_checkbox)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_3.addWidget(self.scrollArea)

        self.OverlaysTabWidget.addTab(self.OverlaysTab, "")
        self.ExperimentalOverlayTab = QWidget()
        self.ExperimentalOverlayTab.setObjectName(u"ExperimentalOverlayTab")
        self.OverlaysTabWidget.addTab(self.ExperimentalOverlayTab, "")

        self.verticalLayout_4.addWidget(self.OverlaysTabWidget)


        self.verticalLayout_2.addWidget(self.ImageOptionsBox)

        self.ActionButtons = QGroupBox(self.ControlsBox)
        self.ActionButtons.setObjectName(u"ActionButtons")
        sizePolicy3.setHeightForWidth(self.ActionButtons.sizePolicy().hasHeightForWidth())
        self.ActionButtons.setSizePolicy(sizePolicy3)
        self.verticalLayout_6 = QVBoxLayout(self.ActionButtons)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.repair_junctions_pushbutton = QPushButton(self.ActionButtons)
        self.repair_junctions_pushbutton.setObjectName(u"repair_junctions_pushbutton")

        self.verticalLayout_6.addWidget(self.repair_junctions_pushbutton)

        self.export_svg_pushbutton = QPushButton(self.ActionButtons)
        self.export_svg_pushbutton.setObjectName(u"export_svg_pushbutton")
        self.export_svg_pushbutton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout_6.addWidget(self.export_svg_pushbutton)


        self.verticalLayout_2.addWidget(self.ActionButtons)


        self.gridLayout.addWidget(self.ControlsBox, 0, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 37))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.ImageTabWidget.setCurrentIndex(0)
        self.OverlaysTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Measure Medial Axis", None))
        self.VisualizerBox.setTitle("")
#if QT_CONFIG(tooltip)
        self.gb_visualizer.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.gb_visualizer.setTitle("")
        self.load_image_pushbutton.setText(QCoreApplication.translate("MainWindow", u"Load Image", None))
        self.clear_image_pushbutton.setText(QCoreApplication.translate("MainWindow", u"Clear Image", None))
        self.ControlsBox.setTitle("")
        self.sliders_groupbox.setTitle("")
        self.isovalue_label.setText(QCoreApplication.translate("MainWindow", u"Isovalue", None))
        self.stroke_width_label.setText(QCoreApplication.translate("MainWindow", u"Stroke Width", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Object Angle Threshold", None))
        self.ImageOptionsBox.setTitle("")
        self.original_image_radiobutton.setText(QCoreApplication.translate("MainWindow", u"Original Image", None))
        self.distance_radiobutton.setText(QCoreApplication.translate("MainWindow", u"Distance Function", None))
        self.clean_canvas_radiobutton.setText(QCoreApplication.translate("MainWindow", u"Clean Canvas", None))
        self.ImageTabWidget.setTabText(self.ImageTabWidget.indexOf(self.ImageVisualizationTab), QCoreApplication.translate("MainWindow", u"Image", None))
        self.upsampling_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))
        self.upsampling_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"2x Naive", None))
        self.upsampling_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"4x Naive", None))

        self.upsampling_combobox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Upsampling Technique", None))
        self.ImageTabWidget.setTabText(self.ImageTabWidget.indexOf(self.upsampling_tab), QCoreApplication.translate("MainWindow", u"Upsampling", None))
        self.voronoi_diagram_checkbox.setText(QCoreApplication.translate("MainWindow", u"Voronoi Diagram", None))
        self.level_set_contour_checkbox.setText(QCoreApplication.translate("MainWindow", u"Boundary Contour", None))
        self.object_angle_checkbox.setText(QCoreApplication.translate("MainWindow", u"Object Angle Measure", None))
        self.circumradius_checkbox.setText(QCoreApplication.translate("MainWindow", u"Circumradius Measure", None))
        self.stroke_graph_checkbox.setText(QCoreApplication.translate("MainWindow", u"Stroke Graph", None))
        self.OverlaysTabWidget.setTabText(self.OverlaysTabWidget.indexOf(self.OverlaysTab), QCoreApplication.translate("MainWindow", u"Overlays", None))
        self.OverlaysTabWidget.setTabText(self.OverlaysTabWidget.indexOf(self.ExperimentalOverlayTab), QCoreApplication.translate("MainWindow", u"Experimental", None))
        self.ActionButtons.setTitle("")
        self.repair_junctions_pushbutton.setText(QCoreApplication.translate("MainWindow", u"Repair Junctions", None))
        self.export_svg_pushbutton.setText(QCoreApplication.translate("MainWindow", u"Export SVG", None))
    # retranslateUi

